FROM node:20-alpine AS build
WORKDIR /usr/src
RUN apk add --no-cache git \
 && git clone https://github.com/sec-o-simple/product-database.git \
 && cd product-database/client \
 && npm install

WORKDIR /usr/src/product-database/client/

ENTRYPOINT [ "npm", "run", "dev" ]

EXPOSE 3000
VOLUME /config