services:

  product-database-server:
    container_name: product-database-server
    build:
      context: ./
      dockerfile: Dockerfile.server
    env_file:
      - ./config/product-database.server.env
    ports:
      - 9999:9999
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:9999/api/v1/health || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  product-database-client:
    container_name: product-database-client
    build:
      context: ./
      dockerfile: Dockerfile.client
    env_file:
      - ./config/product-database/product-database.client.env
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:3000 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      product-database-api:
        condition: service_healthy
